# **Suggested Timeline**

**Integrated Marine Science Exam** (IMSE; *optional*)

- Recommended at the end of the second semester
- Optional comprehensive exam across the four core disciplines of oceanography

**Committee formation**

- Recommended by the end of the second semester

**Prospectus** (i.e., proposal)

- By the end of the third semester; includes written and oral components delivered to your committee (also see Scheduling of Written Products)

**Candidacy qualifying exams** (PhD students)

- By the end of the sixth semester

**Defense** (also see Scheduling of Written Products)

- Master's Student: typically by sixth semester
- Doctoral Student: typically by tenth semester
 
**Thesis/dissertation submission to Graduate School**

- Typically the same semester as defense (always after defense)
- Be sure to check the deadlines with the Graduate School for thesis/dissertation submission and application for graduation
  
*Notes: 1) That “semesters” here apply to fall and spring only, not summers, although you are expected to work in the summer. 2) that although this isn’t a strict timeline, it gives an idea of where you should be at different stages of your graduate career*
