# **General Expectations**

## Read, read, read
Scholarship in science revolves around communication of findings, and the most efficient way to do this is by reading the literature. Learn how to read scientific literature and enjoy the process. Over the course of grad school, you will read thousands of papers (at least you should). At times you will read 4-5 papers per day. Know the literature.Know the classics. Know the frontier of your topics. I will provide you a list of books and peer-reviewed articles you’re required to read, but this is just to get you started. When you’re reading a paper, make note of cited papers that grab your interest and then read those. Have fun exploring papers during literature searches (I suggest using Web of Science, but some also like Google Scholar). Keep up with new literature by subscribing to both Tables of Contents of your favorite journals and Topics of Choice …read, read, read! 

## Write, write, write
Scientific writing is a skill that needs to be developed and refined. The only way to get better at it is to write a lot. A major component of writing is editing. Learning to edit your writing as well as that of others is very important. Write often and exchange your written products with other students to receive feedback. Before giving a written product to me, it should go through three external edits by other students (This is the “Three Then Me” rule). Learn to receive constructive (err negative) feedback and use it to improve your writing and develop your skills. I don’t expect you to be a perfect scientific writer when you start, but I do expect you to learn from your mistakes and minimize the occurrence of those as you progress through graduate school.

## Quantitative skills
The backbone of science is math and statistics. Take as many stats courses as you can. Your analytical tool box will grow as you take more classes and these may inspire you to create new studies. Biometry and Multivariate Stats are often the most relevant to our lab, but there are others offered at CMS such as Data Analysis Methods (Time Series Analysis) and Ecosystem Modeling. You will never have as good of an opportunity as now to sharpen your quantitative skills. It’s a lot harder to gain those skills after you graduate. 

***Note:*** *I suggest you learn the R programming language; R is open source and has largely become the industry standard, so learning it now will pay off later when you have a job.*

## Soft skills 
Soft skills include communication, interpersonal relationships, management, and leadership skills. Take advantage of your position as a graduate student to develop these in your time here. For example, take the lead on a group project or publication, write an opinion piece for the local newspaper (but please run by me first if you are doing it as a representative of USF CMS), or participate in the lab’s outreach efforts (managing social media, participating in the Science Festival, etc.).

## Regular goals
Complete weekly goal and productivity forms. An important skill to develop is to be able to set and meet your own deadlines. Hold yourself accountable for your own progress. When you first begin grad school, I’ll ask for these each week and we’ll review together. As you progress, we can back off to bi-weekly or monthly updates.

***Note:*** *You will also review how well I am doing as your advisor so that we can continue to improve our working relationship and productivity.*

## Work space
Learn to work in your office (or somewhere on campus where I can find you), not at home. There are several reasons for this.

1) I often need to talk to my students, whether to ask questions, present an opportunity, or respond to an inquiry.
2) Other faculty may also need to access you for the same.
3) Working at home isolates you from collaboration (e.g., water cooler chats that turn into papers or proposals).
4) In most jobs, you will be required to work at work, not at home, so you should become effective at doing so now. 
5) For most people, working at home is distracting, resulting in reduced productivity.

***Note:*** *If you struggle to work on campus, please talk to me about it so we can find a solution.*

## Be communicative
Responsiveness to emails and other communications is important. We live in an era of nearly instant communication. Whether for good or bad, the professional world expects fairly rapid responses to emails. However, do not succumb to the email monster and be a slave to email. If you wait more than 48 hours to respond to an email, it may be interpreted as though you are ignoring it. And that’s not good. If you need time to digest an email before you respond, simply reply back that you have read it and will soon respond once you’re able to give it some thought. It’s also good practice to confirm receipt of notifications or attachments so the sender knows you got them. I suggest setting two to three time blocks a day to respond to emails. This way you have time to focus on emails during those blocks and other time to focus on other tasks.

Communication is key. To have a successful graduate career and beyond it is important that we have a good working relationship. This means having open communication about your research, any problems/concerns, and exciting findings that you have. You are here to learn. If you don’t know something, ask. Remember, you are a student. I don’t expect you to know everything. The better I get to know you, and you get to know me, the more successful you will be. Please keep lines of communication open and make sure I am aware of how things are going for you. I want you to succeed. I will be one of your biggest advocates.

## Be passionate
Find your excitement and passion. Finishing either a masters or a doctorate requires a lot of energy, time, and commitment. Make sure you are excited about your Thesis/ Dissertation. Take time to reflect on which topics you are excited about and which skills you are excited to use. These may change as time goes on and it is important to be honest with yourself about you interests. This does not mean constantly changing your focus or techniques used, but rather to focus your topic and hone your skills that you enjoy doing.

## Time management
Put in the time. It’s hard to be successful in grad school if you treat it like a M-F, 9-5 job. 40 hours per week usually won’t cut it. I can’t tell you that you must work XX hours per week. You’ll need to figure that out on your own. But I can tell you that in grad school I put in at least 60 hours per week and often up to 80. 

Punctuality is also very important. I shouldn’t have to point this out, but the culture in academia can sometimes be a bit gray on this. Even being one minute late sends the wrong message. When you are late, you send a message to those waiting on you that your time is more important than theirs. Conversely, arriving on time or even a few minutes early reflects that you are engaged and interested and value the purpose of the meeting. This applies to everything involving a set meeting time, whether it’s a class, field work, lab meetings, meetings with a colleague, etc. 

Deadlines are the reality of the career you have chosen (and most careers for that matter). Take them seriously. This of course applies to deadlines established externally (e.g., due date of a fellowship application), but also internally with colleagues (e.g., getting a ms draft to me). 

Be judicious with your time commitments. During graduate school you will have the opportunity to join many groups, contribute to many collaborations, and partake in many projects. However, this can lead to over commitment. An important skill to develop is the ability to say “no” to certain opportunities and know which ones to say “no” to. The ultimate goal of graduate school is to graduate; therefore, make sure the majority of your time is dedicated towards those tasks required to graduate (required classes, examinations, research, and publishing).