# **Scheduling of Written Products**
## Prospectus, thesis, and dissertation
- Check with the Graduate School or Sami to get the ETD deadline for the semester you are planning to graduate. Plan your defense a minimum of THREE weeks prior to the ETD deadline to allow time for edits before it is due.
- Give me a very polished version of the ms EIGHT WEEKS before committee meeting (see above about Three Then Me). This allows time for one to two edits between you and me before submitting to committee.
- Give the edited ms to your entire committee FOUR WEEKS before committee meeting. This allows your committee to have two weeks prior to the mandatory Sufficiency Meeting, which has to occur at least two weeks prior to your defense. 

## How to schedule a committee meeting
- First, understand that your committee members are all very busy, so scheduling a meeting far in advance (i.e., 2-3 months) is key
- Once you have a target time window of 2-3 weeks, check with Chris for availability. Then, based on his availability, send an email to your committee to ask for their general availability during that time. Will they be around or traveling? 
- Check with Flo for room availability. We usually hold proposal, doctoral candidacy, defense meetings in the MSL Conference Room. It’s best to hold it there for defenses, but we have other options from proposal meetings and candidacy exams (e.g., COT Conf Room, KRC Second Floor Conf Room). 
- Once you have narrowed down some dates that work for everyone and with available meeting space, create a Doodle poll (or any similar service) with time slots and dates for them to choose from. 

*Notes: 1) Stay on top of this process to move it along swiftly. Someone may at first be available on a particular day, but if you don’t lock it in with a set meeting day and time for them to mark on their calendar, their availability may change. 2) You are in charge of reserving the meeting space. Please reserve the room for a total of 3.5 hours, thereby allowing for 30 minutes prior to the meeting and then 3 hours for it.*

## Funding proposals
For both external and internal CMS fellowships:

- Begin early! This is especially important for the highly competitive sources such as NSF.
- Get a polished draft of proposal to me at least **four weeks** before deadline (again, see above about Three Then Me).
- Notify letter writer of request at least **two weeks** before deadline
- When asking for the letter, provide the writer
  a) The description of fellowship, job, etc. (including documentation, web links, etc.)
  b) Your CV, 
  c) Your application including any proposal or research statement materials 
  d) Qualities you want the writer to highlight in the letter (the more ammo you can give the writer, the better they can do to write a very strong letter)

*Note: It is typically expected that your major professor will be one of your letter writers during grad school and even years after it*