# **Scheduling and Preparing for Meetings**

##	Meeting Format 
**Proposal**: 

- Ideally this are a round-table style discussion with the intension of making sure your questions and study design are logical, based on solid scientific premise, possible to accomplish in a graduate school time frame, and will result in high-quality publications. You will prepare a 10-15 minute presentation on your proposal with a standard introduction to the topics and concepts, study questions, study design, predictions (if possible – and they should be), and a timeline.

**PhD Comps** (Candidacy): 

- Believe it or not, I found my candidacy exam to be one of the most fulfilling aspects of my graduate training. You will never have this amount of time to dedicate to reading and sharpening your expertise in your field of study. For the exam, we typically have two rounds of questions with the first round fairly specific to your research and the second round extending more broadly to see gauge the limits of your knowledge in the field. We all want you to do well. Try to have fun with it! 

**Sufficiency**: 

- The format from this meeting can be anything from everyone providing feedback over email to having a formal gathering. The goal here is to make sure there are no surprises at the defense from any committee members regarding their opinion of your research. I won’t let you have this meeting until I think you are ready, so it should primarily be a formality. 

**Defense**: 

- You have made it to your defense! Congratulations, you have much to be proud of. You will prepare a 45-50 min presentation for the public (invite your friend, family, etc), followed by 10-15 min of Q&A from them. We will then take a short 5-10 min break and then reconvene with the committee for the second part of the defense. Similar to the candidacy exam, each committee member can ask any question and there are usually 1-2 rounds of questions. Unlike the candidacy exam, the questions are usually fairly specific to your research, ways to improve the manuscripts for publication, and discussions about future research. Again, this is your day. Have fun with it! 

## What to bring to a committee meeting:
There are forms required for each meeting. Please check here for the most up to date links for them: [USF CMS Student Forms](https://www.marine.usf.edu/education/current-students/forms/). Please print the forms with appropriate information filled in for each (names for you and your committee members, date, etc.).

**Proposal meeting**: 

- Committee Appointment Form (1 total), 
- Proposal SACS Eval Form (rubric; 1 for each committee member).

***Note****: You may (and probably should) have your committee sign the appointment form as soon as you form it as faculty receive teaching credit for the time served on your committee*

**PhD Comps** (Candidacy):

- Candidacy Approval Form (1 total)
- PhD Comp Exam SACS Eval Form (rubric; 1 for each committee member). 

**Sufficiency** (i.e., request for defense):

- Request for Defense Form (1 total)

**Defense**:

- Successful Defense Form (1 total)
- Certificate of Approval (1 total),
- Written SACS Eval Form (rubric; 1 for each committee member), 
- Defense SACS Eval Form (rubric; 1 for each committee member).

***Note****: For all meetings, I think it is a sign of appreciation for your committee’s time to bring light refreshments*